# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20161002_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 10, 4, 15, 50, 42, 186621, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
